// <auto-generated />
using System;
using Gruppe5Projekt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gruppe5Projekt.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617161107_AddIstDemoToLehrveranstaltung")]
    partial class AddIstDemoToLehrveranstaltung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Gruppe5Projekt.Models.Kapitel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kapitelnummer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LehrveranstaltungId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorlesungsfolien")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LehrveranstaltungId");

                    b.ToTable("Kapitel");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.Lehrveranstaltung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dozentenname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IstDemo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lehrveranstaltungen");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.MCAntwortOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Antworttext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IstRichtig")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MCFrageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MCFrageId");

                    b.ToTable("MCAntwortOptionen");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.MCFrage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fragentext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KapitelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KapitelId");

                    b.ToTable("MCFragen");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.Pruefung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("LehrveranstaltungId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LehrveranstaltungId");

                    b.ToTable("Pruefungen");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.PruefungMCFrage", b =>
                {
                    b.Property<int>("PruefungId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MCFrageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PruefungId", "MCFrageId");

                    b.HasIndex("MCFrageId");

                    b.ToTable("PruefungMCFragen");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.Kapitel", b =>
                {
                    b.HasOne("Gruppe5Projekt.Models.Lehrveranstaltung", "Lehrveranstaltung")
                        .WithMany("Kapitel")
                        .HasForeignKey("LehrveranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lehrveranstaltung");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.MCAntwortOption", b =>
                {
                    b.HasOne("Gruppe5Projekt.Models.MCFrage", "MCFrage")
                        .WithMany("AntwortOptionen")
                        .HasForeignKey("MCFrageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MCFrage");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.MCFrage", b =>
                {
                    b.HasOne("Gruppe5Projekt.Models.Kapitel", "Kapitel")
                        .WithMany("MCFragen")
                        .HasForeignKey("KapitelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kapitel");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.Pruefung", b =>
                {
                    b.HasOne("Gruppe5Projekt.Models.Lehrveranstaltung", "Lehrveranstaltung")
                        .WithMany("Pruefungen")
                        .HasForeignKey("LehrveranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lehrveranstaltung");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.PruefungMCFrage", b =>
                {
                    b.HasOne("Gruppe5Projekt.Models.MCFrage", "MCFrage")
                        .WithMany("PruefungMCFragen")
                        .HasForeignKey("MCFrageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gruppe5Projekt.Models.Pruefung", "Pruefung")
                        .WithMany("PruefungMCFragen")
                        .HasForeignKey("PruefungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MCFrage");

                    b.Navigation("Pruefung");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.Kapitel", b =>
                {
                    b.Navigation("MCFragen");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.Lehrveranstaltung", b =>
                {
                    b.Navigation("Kapitel");

                    b.Navigation("Pruefungen");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.MCFrage", b =>
                {
                    b.Navigation("AntwortOptionen");

                    b.Navigation("PruefungMCFragen");
                });

            modelBuilder.Entity("Gruppe5Projekt.Models.Pruefung", b =>
                {
                    b.Navigation("PruefungMCFragen");
                });
#pragma warning restore 612, 618
        }
    }
}
